on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8.15.1
      uses: actions/setup-node@v1
      with:
        node-version: 8.15.1
    - name: Build and Deploy cms
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.CMS_SECRET }}
        BASE_BRANCH: dev
        BRANCH: gh-pages
        FOLDER: dist/cmsapp
        BUILD_SCRIPT: npm install && npm run build -- --prod